language: php
php:
  - "5.4"
  - "5.3"
branches_only:
  - master
before_script:
  - sudo apt-get install -y --force-yes apache2
  - sudo apt-get update
  - sudo apt-get install libapache2-mod-php5 --fix-missing
  # echo "$(curl -fsSL https://raw.github.com/gist/3803112/dfa616acb4c99e59f314d3a8dbda58d1620e7977/gistfile1.txt)" | sed -e "s,PATH,`pwd`/app,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  # echo "$(curl -fsSL https://raw.github.com/gist/3803191/317d19f5aa2b751d21c772c30ac5a49e4d1000b4/gistfile1.txt)" > app/.htaccess
  - sudo sed -i -e "s,/var/www,$(pwd)/app,g" /etc/apache2/sites-available/default
  - cat /etc/apache2/sites-available/default
  - sudo a2enmod rewrite
  - sudo service apache2 restart
  - mysql -e 'create database usarugby'
  - mysql -u root -e "CREATE USER 'usarugby'@'localhost' IDENTIFIED BY 'usarugby'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON usarugby.* TO 'usarugby'@'localhost' WITH GRANT OPTION;"
  - mysql -u usarugby -pusarugby usarugby < db/schema.sql
  - mysql -u usarugby -pusarugby usarugby < db/data.sql
  - composer install --dev
  - sudo service apache2 restart
  - curl http://127.0.0.1
env:
  - BEHAT_PARAMS='extensions[Behat%5CMinkExtension%5CExtension][base_url]=http://127.0.0.1/'
script:
  - bin/behat --verbose
